FROM flyio/postgres-flex:17.2

# pgvector 설치
RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql-17-pgvector && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
